<a href="https://colab.research.google.com/github/DIPTE/Deep-Geometry-Learning-on-Colab/blob/master/LGR_Net_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!ls

In [ ]:
!nvcc -V

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0


In [ ]:
!pip list

In [ ]:
import os
os.chdir('/content/drive/My Drive')#切换工作目录

In [ ]:
!git clone https://github.com/sailor-z/LGR-Net.git

In [ ]:
import os
os.chdir('/content/drive/My Drive/LGR-Net')#切换工作目录

In [ ]:
!sudo apt-get install build-essential python3-dev libssl-dev libffi-dev libxml2 libxml2-dev libxslt1-dev zlib1g-dev

In [ ]:
!export CUDA_HOME="/usr/local/cuda/"
# export CUDA_HOME=/your/cuda/home/directory/
# export LIBRARY_PATH=$LIBRARY_PATH:/your/cuda/lib64/  (optional)


In [ ]:
!cd ./pt_utils/svd && python setup.py install


running install
running bdist_egg
running egg_info
writing torch_batch_svd.egg-info/PKG-INFO
writing dependency_links to torch_batch_svd.egg-info/dependency_links.txt
writing top-level names to torch_batch_svd.egg-info/top_level.txt
/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py:370: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
writing manifest file 'torch_batch_svd.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'torch_batch_svd' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.7-OGiuun/python3.7-3.7.10=. -fstack-protector-strong -Wformat -Werror=format-security -g -fdebug-prefix-map=/build/python3.7-OGiuun/python3.7-3.7.10=. -fstack-protector-

In [ ]:
!cd ./pt_utils/svd && python test.py

tensor([[-0.4177, -0.4788,  0.4089],
        [ 0.0152,  0.1507,  0.6869],
        [ 0.2137, -0.8317,  0.5926],
        [-0.4852,  0.0358,  0.4711],
        [ 0.3797,  0.2507,  0.8463],
        [-0.2151, -0.6489,  0.4648],
        [ 0.5514,  0.0594,  0.8823],
        [-0.2812, -0.1223,  0.5168],
        [ 0.5919, -0.4246,  0.8158]], device='cuda:0')
tensor([[-0.4177, -0.4788,  0.4089],
        [ 0.0152,  0.1507,  0.6869],
        [ 0.2137, -0.8317,  0.5926],
        [-0.4852,  0.0358,  0.4711],
        [ 0.3797,  0.2507,  0.8463],
        [-0.2151, -0.6489,  0.4648],
        [ 0.5514,  0.0594,  0.8823],
        [-0.2812, -0.1223,  0.5168],
        [ 0.5919, -0.4246,  0.8158]], device='cuda:0')
tensor(-9.4064e-07, device='cuda:0', grad_fn=<SumBackward0>)
False
True
False
tensor([[-1.1258, -1.1524, -0.2506],
        [-0.4339,  0.8487,  0.6920],
        [-0.3160, -2.1152,  0.3223],
        [-1.2633,  0.3500,  0.3081],
        [ 0.1198,  1.2377,  1.1168],
        [-0.2473, -1.3527, -1.6959]

In [ ]:
!pip install torch==1.4.0 torchvision==0.5.0

In [ ]:
!pip install torch==1.9.0+cu102 torchvision==0.10.0+cu102 torchaudio===0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 831.4MB 20kB/s 
     |████████████████████████████████| 22.1MB 226kB/s 
  Found existing installation: torch 1.9.0+cpu
    Uninstalling torch-1.9.0+cpu:
      Successfully uninstalled torch-1.9.0+cpu
  Found existing installation: torchvision 0.10.0+cpu
    Uninstalling torchvision-0.10.0+cpu:
      Successfully uninstalled torchvision-0.10.0+cpu


In [ ]:
!pip install torch===1.4.0+cu100 torchvision===0.5.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 723.9MB 24kB/s 
     |████████████████████████████████| 4.0MB 43.6MB/s 
ERROR: torchtext 0.10.0 has requirement torch==1.9.0, but you'll have torch 1.4.0+cu100 which is incompatible.
  Found existing installation: torch 1.4.0
    Uninstalling torch-1.4.0:
      Successfully uninstalled torch-1.4.0
  Found existing installation: torchvision 0.5.0
    Uninstalling torchvision-0.5.0:
      Successfully uninstalled torchvision-0.5.0


In [ ]:
!python ./train_cls.py

Namespace(SO3=True, batchSize=32, bias=False, decay_rate=0.7, decay_step=100, eval=False, gpu_num='1', knn=32, load=False, lr=0.001, model='./logs/', momentum=0.9, nepoch=300, num_points=1024, outf='./logs/', reg_weight=0.0001, test_interval=1, use_sgd=True, workers=4)
Random Seed:  7230
Using GPU : 1
dataset_len: 9840
Use SGD
/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated A

In [ ]:
!sudo rm /var/lib/apt/lists/* -vf
!sudo apt-get update


In [ ]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.get_device_name())
print(torch.cuda.current_device())

True
1
Tesla P100-PCIE-16GB
0
